DROP TABLE albums;        
DROP TABLE genres;           
DROP TABLE r_artist_genre;
DROP TABLE artists;
DROP TABLE r_albums_artists;  
DROP TABLE r_track_artist;
DROP TABLE audio_features;    
DROP TABLE r_albums_tracks;
DROP TABLE tracks;